apiVersion: v1
kind: Service
metadata:
  name: auth-frontend
  labels:
    app: auth-frontend
spec:
  type: NodePort
  selector:
    app: auth-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081 