name: Build and Slim Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build backend Docker image
        run: |
          docker build -f Dockerfile.backend -t ghcr.io/${{ github.repository_owner }}/auth-backend:latest .

      - name: Slim backend Docker image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: "false"
        with:
          target: ghcr.io/${{ github.repository_owner }}/auth-backend:latest
          tag: slim

      - name: Push slimmed backend Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/auth-backend:slim

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build frontend Docker image
        run: |
          docker build -f front-end/Dockerfile.frontend -t ghcr.io/${{ github.repository_owner }}/auth-frontend:latest ./front-end

      - name: Push frontend Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/auth-frontend:latest 